### ISSUE TITLE
Unexpected result converting lat,lon on sphere to lat,lon on WGS84

### ISSUE THREAD

**Issue by andypbarrett** [OSGeo/proj.4#2860]
I'm trying to convert lat,lon on a sphere to lat,lon on WGS84.  

```
$ cs2cs +proj=lonlat +ellps=sphere +R=6367470 +to +proj=lonlat +ellps=WGS84 in.txt 
0dE	0dN 0.000
10dE	60dN 0.000
60dE	10dN 0.000
0dE	90dN 0.000
0dE	90dS 0.000
45dE	45dN 0.000

$ cat in.txt
0 0
10 60
60 10
0 90
0 -90
45 45
```

#### Expected Output
Latitude on a sphere should be different from latitude on an ellipsoid 

#### Environment Information
 - PROJ version (`proj`)  Rel. 7.0.0, March 1st, 2020
 - Operation System Information Linux version 4.4.0-210-generic (buildd@lgw01-amd64-009) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021

#### Installation method
 Installed via 
`conda install pyproj`

**Comment by rouault** [comment]
Unexpected for you, but expected by design of PROJ. Your source and target CRS lack a datum description. They are just raw ellipsoids, so we don't know how to relate them which each other. If the 2 CRS have the same geocentric origin and axis alignment, then you could add a +towgs84=0,0,0 to each one, and you'd probably get the result you expect

$ echo 10 60 | cs2cs +proj=lonlat +ellps=sphere +R=6367470 +towgs84=0,0,0 +to +proj=lonlat +ellps=WGS84  +towgs84=0,0,0
10dE	60d9'58.406"N 0.000
