### ISSUE TITLE
vgridshift seems to be substituting instead of offsetting

### ISSUE THREAD

**Issue by JordanMcManus** [OSGeo/proj.4#2956]
#### Example of problem
Using this geoid model:
[HT21997.zip](https://github.com/OSGeo/PROJ/files/7590143/HT21997.zip)

```c
cct +proj=vgridshift +grids=/home/jordan/HT21997.gtx
-72.5583230361 46.3233882250 -22.240 0
-72.5583230361   46.3233882250      -30.4348        0.0000
```
#### Problem description

If I open the geoid model (HT21997) and extract a value close to the given position:
```c
-72.55000000 46.31666667 -30.557
```

The [documentation](https://proj.org/operations/transformations/vgridshift.html) for vgridshift says that it should apply the offset found in the grid with the default -1 multiplier.

> The vertical grid shift is done by offsetting the vertical input coordinates by a specific amount determined by the loaded grids.

But here, it seems that it is simply **_substituting_** the grid value without any offsetting.

#### Expected Output

If I am not mistaken in my understanding, I am expecting to see:
```c
cct +proj=vgridshift +grids=/home/jordan/HT21997.gtx
-72.5583230361 46.3233882250 -22.240 0
-72.5583230361   46.3233882250      8.34        0.0000
```
Since this is a known geodetic reference point.

#### Environment Information
 - Rel. 8.2.0, November 1st, 2021
 - Ubuntu 18.04.6 LTS
#### Installation method
 - conda

**Comment by rouault** [comment]
> If I open the geoid model (HT21997) and extract a value close to the given position:
> 
> ```c
> -72.55000000 46.31666667 -30.557
> ```

I suspect the utility you use to extract values must not report the raw value in the file

If using GDAL's gdallocationinfo, we get:

$ echo -72.5583230361 46.3233882250 | gdallocationinfo -wgs84 HT21997.gtx
Report:
  Location: (2083P,1130L)
  Band 1:
    Value: 8.15100002288818

which is consistant with the value you get with cct

That said I'd suspect the .gtx file to be bogus, because the value we get with EGM96 is quite different

$ echo -72.5583230361 46.3233882250 | gdallocationinfo -wgs84 /usr/share/proj/egm96_15.gtx 
Report:
  Location: (430P,175L)
  Band 1:
    Value: -31.1446552276611

Actually... overlapping HT21997.gtx and egm96_15.gtx  in QGIS, I can see that  HT21997.gtx seems to have some vertical mirroring compared to the content of EGM96. So I'd rather suspect the issue to be on the producer of HT21997.gtx

**Comment by JordanMcManus** [comment]
Thanks for the quick reply! That does make sense. I was using the converter that is bundled in [Hydromagic](https://www.eye4software.com/hydromagic/). Do you know another way I can convert this model?

**Comment by rouault** [comment]
what is the source file ?

**Comment by JordanMcManus** [comment]
HT2_1997.byn
Natural Resources Canada file format (.byn)

**Comment by rouault** [comment]
you can use the gdal_translate (https://gdal.org/programs/gdal_translate.html) utility from GDAL to transform a .byn file (https://gdal.org/drivers/raster/byn.html) to a .gtx or GeoTIFF one, both of which can be read by PROJ >= 7

gdal_translate HT2_1997.byn HT2_1997.gtx
or
gdal_translate HT2_1997.byn HT2_1997.tif

**Comment by JordanMcManus** [comment]
Thanks very much for your help! I got it working.
