### ISSUE TITLE
Get Different Result When Transform From EPSG:2362 To EPSG:4326 between pyproj 1.9.6 and pyproj 2.6.1

### ISSUE THREAD

**Issue by qd1308504206** [OSGeo/proj.4#2958]
As title said. 
#### My python Code
```py
import pyproj
from pyproj import Proj

print(pyproj.__version__)
print(pyproj.proj_version_str)
print(pyproj.geodesic_version_str)

#t = Transformer.from_crs(2362, 4326)
p1 = Proj(init='epsg:2362')
p2 = Proj(init='epsg:4326')
x1,y1=(4.00607742131667E7, 4728081.38705645)

x2,y2 = pyproj.transform(p1,p2,x1,y1)
print(x2,y2)

```

#### Code description
1: when I use pyproj 1.9.6
the result is 
```
1.9.6
0.5.20
1.49.3
132.55686355409077 41.16173427687807
```
2: and when I use pyproj 2.6.1
```
2.6.1.post1
7.0.1
1.50.0
132.55696491025617 41.16172937743053
```

#### Problem description
When I transform Point From 2362 to 4326, 
the input is : 4.00607742131667E7, 4728081.38705645
pyproj 1.9.6  result is **132.55686355409077 41.16173427687807**
pyproj 2.6.1  result is **132.55696491025617 41.16172937743053**

**will be same problem between proj 4.4.0 with proj 8.1.0 in c code.**

#### Expected Output
Expected the same result.

Or why this happen?
and Please Tell me Which one is more precise? 

AND the website Transform result is **132.5568637° 41.1617342°** 
the epsg.io result is more closer to "pyproj 1.9.6"
http://epsg.io/transform#s_srs=2362&t_srs=4326&x=40060774.2131667&y=4728081.3870565

#### Environment Information
win10 64bits  pycharm, pyproj, python 3.8.12

#### Installation method
conda

**Comment by rouault** [comment]
The new result is more correct than the previous one. Before PROJ 6, the Transverse Mercator implementation used the the Evenden-Snyder algorithm that diverged beyond 3 degrees of the central meridian (which is the case here since your point is at longitdue ~ 132.5 whereas the central meridian of EPSG:2362 is at 114. Starting with PROJ 6, the more accurate Engsager and Poder formulas is used. See around https://proj.org/operations/projections/tmerc.html#cmdoption-arg-approx

You can get the old results by using a PROJ.4 string that has an explicit +approx flag

See

$ echo 4.00607742131667E7 4728081.38705645 0 |  src/cs2cs -d 8 +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=38500000 +y_0=0 +a=6378140 +b=6356755.288157528 +units=m +no_defs +to +init=epsg:4326
132.55696491	41.16172938 0.00000000

vs

$ echo 4.00607742131667E7 4728081.38705645 0 |  src/cs2cs -d 8 +proj=tmerc +approx +lat_0=0 +lon_0=114 +k=1 +x_0=38500000 +y_0=0 +a=6378140 +b=6356755.288157528 +units=m +no_defs +to +init=epsg:4326
132.55686355	41.16173428 0.00000000

I would note that none of those 2 results is likely to be correct, as they all lack a datum transformation between  the Xian 1980 datum and WGS 84, so results could be off by several 10 of meters or more. But such datum transformation is not published in the sources we use to build the PROJ database, so you're a bit of your own to figure it out.

**Comment by qd1308504206** [comment]
OK @rouault  Thank you so much.

**Comment by qd1308504206** [comment]
In GDAL 3.0+,
we can set Options to get the old value.

CPLSetConfigOption("OSR_USE_APPROX_TMERC", "YES");
