### ISSUE TITLE
Documentation seems to be lacking

### ISSUE THREAD

**Issue by oleg-alexandrov** [OSGeo/proj.4#3508]
I am trying to migrate from Proj4 to recent API. The best documentation I could find is at https://proj-tmp.readthedocs.io/en/docs/development/migration.html

It is rather fragmentary though. There is no example of going from projected coordinates to lon and lat. It is not spelled out what c.lp.lam and  c.lp.phi mean (lon, lat or easting, northing, in what order). The documentation of proj_trans and of PJ_COORD doesn't explain any of that either. 

It would be nice if the current doc could be expanded a bit, as this is a basic usage.

**Comment by kbevers** [comment]
Sure, the docs could be improved. They always can. We're happy to accept pull requests with improvements. 

That doesn't solve your immediate problem. It's been a while since PROJ.4 -> modern PROJ was hot topic but when it was a couple of years ago the mailing list had quite a lot of discussions about how to best do things. I suggest you take a look at the archives: https://lists.osgeo.org/pipermail/proj/ There are other good resources too, especially this write up from the spatialite project: https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6. 

The datatypes are all explained her: https://proj.org/development/reference/datatypes.html

> There is no example of going from projected coordinates to lon and lat

The example program at  https://proj.org/development/quickstart.html does exactly that. It takes geodetic coordinates (lon, lat) converts to UTM and back again.

**Comment by oleg-alexandrov** [comment]
Thank you. This is helpful. Note that the quick start example does not explain how to use the proj_create() function, which is what is needed to create a projection. It only has an example for proj_create_crs_to_crs(), so conversions among projections.

**Comment by kbevers** [comment]
> It only has an example for proj_create_crs_to_crs(), so conversions among projections

That's a bit of an understated, I'd say. It provides access to more or less any transformation between coordinate reference systems available in our database. It's definitely possible to do a conversion from geodetic coordinates, let's say in ETRS89 (EPSG:4258), to a projection on top of that like UTM32N (EPSG:25832). The old style of PROJ.4-strings are also valid input (basically what you would put into `pj_init` in the olden days). 

With that said, yes, `proj_create` is different and it offers more flexibility and room for shooting yourself in the foot. The last point is the reason we didn't put into the quickstart example. It's not what most people need.

**Comment by oleg-alexandrov** [comment]
Thank you for explaining these things.

I am obviously a new user. My issue is that proj_create_crs_to_crs(), for all its wonders, can't do the job of proj_create(), which is project from lon-lat to projected coordinates and vice-versa when a single projection exists. I did a lot of googling outside the official documentation to find out this simple thing and how to use it. 

Granted, one could use proj_create_crs_to_crs() with one CRS being say long-lat, but that is not explained either, and one should set up a datum too, identical to what is used for the other projection.

**Comment by oleg-alexandrov** [comment]
Got fixed in https://github.com/OSGeo/PROJ/pull/3515.
