### ISSUE TITLE
proj_pj_info on transformer from EPSG:4326 to EPSG:26917 changed with only best addition

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#3619]
Related:

- https://github.com/OSGeo/PROJ/issues/3607
- https://github.com/pyproj4/pyproj/issues/1230

#### Example of problem
```c
PJ* transformer = proj_create_crs_to_crs(NULL, "EPSG:4326", "EPSG:26917", NULL)
PJ_PROJ_INFO proj_info = proj_pj_info(transformer)
```
#### Problem description

Without grids or PROJ_NETWORK:

The `id` and `description` resolved to a single result in PROJ 9.1:
```
id -> pipeline
description -> Inverse of NAD83 to WGS 84 (1) + UTM zone 17N
```
With PROJ master, the `id` and `description` resolve to:
```
id -> unknown
description -> unavailable until proj_trans is called
```

#### Expected Output

Noticed a change in behavior that was unexpected. Just wanted to verify that this behavior is desired.

#### Environment Information
 - Ubuntu 22

#### Installation method
 - conda & from source

**Comment by snowman2** [comment]
Thanks for working on this @rouault 👍. I re-ran the tests and it still failed for some reason: https://github.com/pyproj4/pyproj/actions/runs/4094135515/jobs/7181877475

**Comment by rouault** [comment]
> I re-ran the tests and it still failed for some reason: https://github.com/pyproj4/pyproj/actions/runs/4094135515/jobs/7181877475

I couldn't add a test for your exact reproducer because in the PROJ data used for tests there are a few grids that can be used for NAD83 -> WGS 84, and thus there are several transformation candidates.
So obviously all this shows that there are subtle differences with the ONLY_BEST changes for some (source_crs, target_crs) tuples. I'm not sure what your test case wanted to test, but I suggest you change your test to use the EPSG:4326+3855 to EPSG:4979 test I added if you want to test the situation "there are several transformation candidates, but just one can be instanciated", or something that doesn't involve datum changes at all (like EPSG:4326 to EPSG:32631) if your test want to just checks proj_pj_info() base behaviour.

**Comment by snowman2** [comment]
Sounds good - thanks for verifying that the behavior change is okay and for the suggestions 👍

**Comment by snowman2** [comment]
Update: I updated the test to use `EPSG:4326+3855 to EPSG:4979` (https://github.com/pyproj4/pyproj/pull/1241) and found some differences between PROJ 9.1.1 and the latest 9.2.0 that seemed worth mentioning:

1.  `proj_get_area_of_use` returned `World` in 9.1.1 and returns `NULL` in 9.2.0.
2.  `proj_get_type` used to be `PJ_TYPE_OTHER_COORDINATE_OPERATION` and is  `PJ_TYPE_UNKNOWN` in 9.2.0.

**Comment by rouault** [comment]
I suggest you change your test to use EPSG:4326+5773 (EGM 96 instead of EGM2008). Because there's one single transformation between EGM 96 and WGS 84 ellipsoidal height, whereas there are 2 for EGM20008 -> WGS84 (one using Und_min1x1_egm2008_isw=82_WGS84_TideFree.gz being not actually usable by PROJ, but PROJ has no real way of anticipating it)
