### ISSUE TITLE
PROPOSAL: Allow passing in pivot CRS in proj_create_crs_to_crs_from_pj/cs2cs

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#3622]
Related: https://github.com/OSGeo/PROJ/blob/c85596492960d390ce28136b453742c36e529d93/src/proj.h#L1349-L1355

See: --pivot-crs in https://proj.org/operations/operations_computation.html

Thoughts?

**Comment by rouault** [comment]
People who use proj_create_crs_to_crs_from_pj() are probably the ones who don't want to think about the details of how the transformation will be done, and hope for the best. Using a given intermediate CRS requires already some expertise, and in general more in a projinfo use case where you want to review what PROJ has infered, because sometimes it might have little geodesic meaning. So it is not obvious it is appropriate to add a pivot_crs option to proj_create_crs_to_crs_from_pj(). I wouldn't object if someone wants to add it, but not something I'd spontaneously do myself

And that would be totally useless for https://github.com/geopandas/geopandas/issues/2787#issuecomment-1426982871. Using WGS84 as an intermediate to do ED50 -> BD50 doesn't help given that there's no known transformation between WGS84 and BD50. Actually a quick grep of data/sql/* shows that there's no known transformation between BD50 and any other datum (other than BD50 (Brussels) but this is basically the same datum with a different prime meridian, so not a real datum transformation)

**Comment by snowman2** [comment]
Thanks for giving further insight into the matter. That makes a lot of sense. I think making it a more advanced feature sounds reasonable to me.
