### ISSUE TITLE
CMake cannot find PROJ

### ISSUE THREAD

**Issue by AmirInt** [OSGeo/proj.4#3682]
I installed PROJ using apt based on [this guide](https://proj.org/install.html#debian) and could use its APIs when compiling with g++ and with the flag `-lproj` provided. But using it in my CMake project based on [this](https://proj.org/development/cmake.html), cmake complained that it could not find `PROJConfig.cmake` or `proj-config.cmake`.
I removed PROJ and installed version 9.1.1 from source, and it fixed the issue. I'm on an Ubuntu 22.04 on WSL2 (Windows 11).

**Comment by rouault** [comment]
As far as I can see, https://packages.ubuntu.com/jammy/amd64/libproj-dev/filelist doesn't provide them. This is likely due to those builds still using the autotools build system that has been removed in PROJ 9.
If you want to link against PROJ versions that don't ship CMake configuration files, you'll have to use a FindPROJ.cmake custom module, like in https://github.com/OSGeo/gdal/blob/master/cmake/modules/packages/FindPROJ.cmake

**Comment by dg0yt** [comment]
You should also be able to use PROJ via pkg-config, i.e. via CMake's `pkg_check_modules()`. I would recommend to make use of the `IMPORTED_TARGET` option.
https://cmake.org/cmake/help/latest/module/FindPkgConfig.html
