### ISSUE TITLE
Translate command into equivalent c++ function

### ISSUE THREAD

**Issue by alionteo** [OSGeo/proj.4#3688]
I want to use this to translate WSG84 to UMT and I am able to execute this command from terminal
echo 56 12 | cs2cs +init=epsg:4326 +to +init=epsg:25832 with output as 6231950.54	1920310.71 0.00 now trying to achieve it from c++ code and here is my way

```
PJ_CONTEXT *C;
PJ *P;
C = proj_context_create();

P = proj_create_crs_to_crs(C, "EPSG:4326", "EPSG:6677", NULL);
PJ_COORD input_coords, output_coords;
input_coords = proj_coord(56,12, 0, 0);
output_coords = proj_trans(P, PJ_FWD, input_coords);
std::string result = "";
result.append(std::to_string(output_coords.xy.x)+","+ std::to_string(output_coords.xy.y));
proj_destroy(P);
proj_context_destroy(C);


But it return to me same coordinates what i send in input i.e, 56,12. @rouault   Kindly help thanks

**Comment by busstoptaktik** [comment]
@alionteo this is not a "feature request", but a usage question. And as already said: Direct your usage questions to the mailing list, where you will find the community of PROJ users.

**Comment by alionteo** [comment]
@busstoptaktik  yes its a usage question for that I wait for someone's email for hours , instead someone can answer here? Atleast there should be some examples to work with. documentation of repo is really a crap. I think you are more interested in closing a ticket than answering it, very strange.

**Comment by busstoptaktik** [comment]
@alionteo I gave clear instructions on how to reach the relevant community (i.e. users for usage questions). Please stop adding additional noise to this channel, which is for development *of* PROJ, not *with* PROJ.

If you find documentation crappy, a pull request with improvements is very welcome - you can discuss what may be good candidates for improvement with other PROJ users on the PROJ mailing list, then go ahead and contribute.

Also you are deeply wrong in thinking that I am "more interested in closing a ticket than answering it": I am interested in removing irrelevant noise from the issue tracker (so developers can concentrate on resolving issues, rather than sifting through usage requests), and directing it to a communication channel, where it will be signal rather than noise.

So please let this thread stop here.

**Comment by alionteo** [comment]
You can call it a "noise" for me its a valid question, I am not a c/c++ guys to contribute into it, thanks for your kind suggestions.

**Comment by busstoptaktik** [comment]
It is definitely a valid question, that could get valid answers if asked in the proper forum. Which is not here.
