### ISSUE TITLE
Helmert transform: how to

### ISSUE THREAD

**Issue by xakod** [OSGeo/proj.4#3737]
Hello! I wanna use helmert transfrom from command line (https://proj.org/operations/transformations/helmert.html). I try example
```
proj=helmert convention=coordinate_frame x=0.67678    y=0.65495   z=-0.52827 rx=-0.022742 ry=0.012667 rz=0.022704  s=-0.01070
```
but I see error:
```
proj=helmert convention=coordinate_frame x=0.67678    y=0.65495   z=-0.52827 rx=-0.022742 ry=0.012667 rz=0.022704  s=-0.01070
proj_create: unrecognized format / unknown name
Rel. 8.2.1, January 1st, 2022
<proj>:
projection initialization failure
cause: Unknown error (code 4096)
program abnormally terminated
```
I tried also:
```
proj +proj=helmert convention=coordinate_frame x=0.67678    y=0.65495   z=-0.52827             rx=-0.022742 ry=0.012667 rz=0.022704  s=-0.01070
```
```
cct +proj=helmert convention=coordinate_frame x=0.67678    y=0.65495   z=-0.52827             rx=-0.022742 ry=0.012667 rz=0.022704  s=-0.01070
```
But it also does not work.
I have no ideas how to do it. What I do wrong? Thank you.

**Comment by rouault** [comment]
you need to use cct, and add + in front of each parameter:
```
cct +proj=helmert +convention=coordinate_frame +x=0.67678 +y=0.65495 +z=-0.52827 +rx=-0.022742 +ry=0.012667 +rz=0.022704 +s=-0.01070
```

**Comment by xakod** [comment]
@rouault thank you, I try but looks like it does nothing
![изображение](https://github.com/OSGeo/PROJ/assets/26579016/ca4fc874-d441-431e-87eb-b62e6ab5c8d4)
cct does not print any messages or result

**Comment by xakod** [comment]
@rouault don't understand why you closed issue. In your example cct waits here https://github.com/OSGeo/PROJ/blob/master/src/apps/cct.cpp#L446 for input files but there are no files.

**Comment by kbevers** [comment]
@Jihadist there are several reasons why the issue was closed:

1. This is our issue tracker, not a forum for asking help about the use of PROJ. We've got the mailing list for that, as you can read in our community guidelines: https://proj.org/community/channels.html. 
2. You got a proper answer for your question. If you'd spend two minutes trying reading the manual you'd have figured out that `cct` and other PROJ applications waits for user input once a instantiated. You can also pipe input to them if you prefer that:

```
$ echo 3586469.6568  762327.6588  5201383.5231  0.0000 | cct +proj=helmert +convention=coordinate_frame +x=0.67678 +y=0.65495 +z=-0.52827 +rx=-0.022742 +ry=0.012667 +rz=0.022704 +s=-0.01070
 3586470.0597    762327.3373  5201383.2435        0.0000
```

(3. most people aren't too keen on interacting with a self-proclaimed jihadist)

**Comment by xakod** [comment]
@kbevers thank you!
