### ISSUE TITLE
Omerc +gamma: Point outside projected domain

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3749]
```
for i in `seq 77 1 88`; 
do echo $i; 
echo 100 100 | 
proj -I +proj=omerc +lat_0=10 \
 +lonc=10 +gamma=$i||
break; done

7710d0'3.537"E    10d0'2.982"N
78
10d0'3.572"E    10d0'2.941"N
79
10d0'3.625"E    10d0'2.876"N
80
10d0'3.766"E    10d0'2.693"N
81
proj_create: Error 2050 (Point outside of projection domain)
Rel. 9.2.1, June 1st, 2023
<proj>:
projection initialization failure
cause: Point outside of projection domain
program abnormally terminated
```

**Comment by jjimenezshaw** [comment]
Hi @jidanni 
This is not a well formed issue. You do not explain what is the problem, what do you expect, what have you researched before...
Actually I do not know if your problem is the "program abnormally terminated" or the fact that there is no transformation for gamma=82

Said that, the reason of the termination is an error/exception in C++ code, in particular in https://github.com/OSGeo/PROJ/blob/7e10ddc628e014c317c18d4bf464ea8947ce082b/src/projections/omerc.cpp#L59-L60
(now that I realize that your projection is inverse, look down in the same file. There are similar errors.)

I suffered it some time ago when I was trying to use oblique transverse Mercator in a general way (not for an specific CRS defined in EPSG), and I found that it was not covering all the possible angles.
The formulas for `omerc` are not "continuous". One case is this exception mentioned in line 59 (yes, I know it is there to avoid a NaN later). Another one is in https://github.com/OSGeo/PROJ/blob/7e10ddc628e014c317c18d4bf464ea8947ce082b/src/projections/omerc.cpp#L65 . Doing some experiments I found "discontinuities" in the outputs. Maybe later this year I have time to do a full analysis of those discontinuities to share it here.

I tried to understand the formulation in Snyder book, but it was not clear to me. Can anybody explain to me how the `gamma` parameter works in this projection? I got confused with projections with gamma=90 (Like in Swiss LV95). Is that "oblique"?

**Comment by rouault** [comment]
Looking at Snyder / EPSG guidance note 7-2, I've the impression that specifying gamma without alpha is a PROJ extension, and given the maths involved, there is a maximum value for gamma that is roughly 90° - lat_0 . Error caught and improved message in https://github.com/OSGeo/PROJ/pull/3750

**Comment by jidanni** [comment]
All I know is, it would be great, if there were an example map, say of
~~Arizona U.S.A.,~~ Baja California etc. "slanted" states (not just the whole world) with the meanings of +alpha and +gamma indicated upon it. Else not too many people can understand what the PROJ documentation is trying to say.

https://gis.stackexchange.com/questions/380535/creating-an-oblique-mercator-projection-using-proj-and-qgis
https://gis.stackexchange.com/questions/375104/can-i-visualize-a-spatial-movement-in-a-room-data-using-qgis/377710#377710

**Comment by jidanni** [comment]
> maximum value for gamma that is roughly 90° - lat_0

Maybe https://proj.org/en/9.2/operations/projections/omerc.html should mention this, to help users be more prepared...
