### ISSUE TITLE
Issue with 3d for EPSG:4978 to EPSG:27700

### ISSUE THREAD

**Issue by romaintha** [OSGeo/proj.4#3932]
hello,
We are facing an issue ( on the z axis) with a transformation from EPSG:4978 to EPSG:27700. 

Before running `projsync --all`, the output of:

 `echo 3977163.2951385537 -18548.855688361964 4969626.955513516 | cs2cs +init=epsg:4978 +to +init=epsg:27700 --3d`

is :

`520327.98	181233.65 45.92` 

Once I run `projsync --all`, for the same cs2cs command I get:

`520326.39	181233.48 92.24`

The z value went from 45.92 to 92.24. Is that expected? 

#### Environment Information
 - PROJ version Rel. 9.1.1, December 1st, 2022
 - Debian GNU/Linux 12

#### Installation method
 - apt-get install proj-bin

**Comment by rouault** [comment]
> Is that expected?

sort of. The fundamental issue is that you are converted between a 3D CRS (EPSG:4978) and a 2D one (EPSG:27700). Hence what happens with Z is pretty much undefined. A pedantic version of PROJ could potentially just error out.
In the first version without grid, a 3D Helmert transformation is done between Airy and WGS 84, which is quite dubious since Airy ellipsoidal height must not be something well defined and thus a 3D Helmert quite optimistic
With grids, a 2D horizontal shift is done and the ellipsoidal height resulting from the geocentric -> lat, lon, ellipsoidal height conversion is kept unmodified.

You'd get more meaning full result if transforming to EPSG:27700+5701 (that is with ODN height):

$ echo 3977163.2951385537 -18548.855688361964 4969626.955513516 | PROJ_NETWORK=ON bin/cs2cs EPSG:4978 EPSG:27700+5701 
520326.39	181233.48 46.48
