### ISSUE TITLE
Invalid PROJ string syntax on cct man page example

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#4017]
The cct man page has invalid syntax.
```
$ man cct | grep step.*step | sh -x
+ cct +proj=pipeline +proj=utm +ellps=GRS80 +zone=32 +step +step +inv
proj_create: Error 1025 (Invalid PROJ string syntax): pipeline: 
Pipeline: proj= operator before first step not allowed
cct: Bad transformation arguments - (Invalid PROJ string syntax)
    'cct -h' for help
```
I'm not exactly sure what the author intended, so can't fix it.

**Comment by kbevers** [comment]
> I'm not exactly sure what the author intended, so can't fix it.

I know what the intention was: Demonstrating a (probably too) clever use of the pipeline operator. This would have worked around the time the pipeline operator was introduced but since then things have changes slightly without the docs being updated. It happens.

So, the clever pipeline usage here is leveraging [rule 4 of the operator](https://proj.org/en/9.3/operations/pipeline.html):

> Parameters added before the first `+step` are global and will be applied to all steps

It is however not legal to have another operator, e.g. `+proj=utm`, be part of those global parameters. It used to be allowed.

A corrected pipeline for the `cct` docs would be:

```
cct +proj=pipeline +ellps=GRS80 +zone=32 +step +proj=utm +step +proj=utm +inv 
```

**Comment by jidanni** [comment]
Ah, no wonder!
Well please upload your changes because I'll only screw it up if I try. Thanks!
