### ISSUE TITLE
There are cases where the results from cs2cs differ between PROJ 5.2.0 and PROJ 7.0.1.

### ISSUE THREAD

**Issue by honjo2** [OSGeo/proj.4#4060]
After updating from PROJ 5.2.0 to PROJ 7.0.1, I noticed that the results from cs2cs have changed. For example, the results change in the following case:

```bash
echo 130.51180595163692 33.287626363135914 | cs2cs +init=epsg:4301 +to +init=epsg:3857
```

With PROJ 5.2.0, the result is `14528246.94 3933983.40 55.58`, but with PROJ 7.0.1, it becomes `14528248.51 3933990.34 0.00`. 

However, there are cases where the latitude and longitude do not change the result. For instance, the results do not change in the following example:

```bash
echo 139.7 35.7 | cs2cs +init=epsg:4301 +to +init=epsg:3857
```

In PROJ 5.2.0, the result is `15550973.41 4259863.42 37.03`, and in PROJ 7.0.1, it remains `15550973.41 4259863.42 0.00`.

Is it possible to correct this so that the results are the same as with PROJ 5.2.0?

**Comment by rouault** [comment]
PROJ >= 6 results should be generally "better" than past PROJ versions
In particular for this transformation where PROJ will select an appropriate datum transformations between Tokyo datum and WGS 84 based on the extent.

```
$  echo 130.51180595163692 33.287626363135914 | PROJ_DEBUG=2 cs2cs +init=epsg:4301 +to +init=epsg:3857
[...]
Using coordinate operation axis order change (2D) + Tokyo to WGS 84 (5) + Popular Visualisation Pseudo-Mercator
14528248.51	3933990.34 0.00
```

```
$ echo 139.7 35.7 | PROJ_DEBUG=2 cs2cs +init=epsg:4301 +to +init=epsg:3857
[...]
Using coordinate operation axis order change (2D) + Tokyo to WGS 84 (108) + Popular Visualisation Pseudo-Mercator
15550973.41	4259863.42 0.00
```

Note that 2 different datum shifts have been used.

To get the same result as PROJ 5.2, which used the default "Tokyo to WGS 84 (108)" datum shift, you can use
```
$ echo 33.287626363135914 130.51180595163692 0 | cct -d 2 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=bessel +step +proj=helmert +x=-146.414 +y=507.337 +z=680.507 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 
  14528246.94     3933983.40          0.00           inf
```

This is the first pipeline output by:
```
projinfo -s EPSG:4301 -t EPSG:3857 --spatial-test intersects|less
```

**Comment by honjo2** [comment]
@rouault PostgreSQL 12.14 on RDS includes the following PostGIS:
```sql
=> SELECT PostGIS_Full_Version();
                                                                        postgis_full_version                                                                        
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.7 aafe1ff" [EXTENSION] PGSQL="120" GEOS="3.8.2-CAPI-1.13.4" PROJ="7.0.1" LIBXML="2.9.1" LIBJSON="0.13.1" LIBPROTOBUF="1.3.2" WAGYU="0.5.0 (Internal)"
(1 row)
```
How can I achieve same result to PROJ 5.2 in this environment?

**Comment by eugenemlee** [comment]
Hi @rouault, I've observed that you closed issue #2756 along with this one, but I believe there's an important concern that hasn't been fully addressed. By analyzing the outputs of `cs2cs` from version 7.2.1 through to 9.3.1, a concerning pattern emerges:

```bash
echo 720000 7500000 | cs2cs -d 10 EPSG:28350 EPSG:4326
```
| PROJ | EPSG | LAT | LON |
|---|---|---|---|
| 7.2.1 | 10.008 | -22.5925932152 | 119.1400057100 |
| 8.0.0 | 10.015 | -22.5925796136 | 119.1400154504 |
| 8.0.1 | 10.018 | -22.5925796136 | 119.1400154504 |
| 8.1.0 | 10.027 | -22.5925794863 | 119.1400157001 |
| 8.2.0 | 10.038 | -22.5925794863 | 119.1400157001 |
| 9.0.0 | 10.054 | -22.5925794863 | 119.1400157001 |
| 9.1.0 | 10.074 | -22.5925794863 | 119.1400157001 |
| 9.2.0 | 10.082 | -22.5925932152 | 119.1400057100 |
| 9.3.0 | 10.094 | -22.5925932152 | 119.1400057100 |
| 9.3.1 | 10.098 | -22.5925932152 | 119.1400057100 |

A bug appears to have been introduced in version 8.0.0, with minor adjustments observed up until version 9.1.0, before reverting back to the behavior seen in 7.2.1 from version 9.2.0 onwards.

This issue significantly impacts us because we rely on AWS RDS PostgreSQL, which locks PROJ to version 8.0.1, leaving us without the option to upgrade or downgrade. We would like to initiate discussions with AWS to consider upgrading to a version >= 9.2.0. However, this requires an acknowledgment of the issue from the PROJ maintainers. Such acknowledgment would not only help in our discussions with AWS but also reassure us that this bug will not reappear in future releases.

Thank you for considering this matter.

*EDIT*
Adding a bit of debug info
```
# PROJ 7.2.1
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded

# PROJ 8.0.0
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
Using coordinate operation Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (2)

# PROJ 8.0.1
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
Using coordinate operation Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (2)

# PROJ 8.1.0
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
Using coordinate operation Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (3)

# PROJ >=9.2.0
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(au_icsm_GDA94_GDA2020_conformal_and_distortion.tif): call fopen(/usr/share/proj/au_icsm_GDA94_GDA2020_conformal_and_distortion.tif) - succeeded
Using coordinate operation Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (1)
```

**Comment by rouault** [comment]
The results of PROJ are expected to change over versions because there are logic adjustment in the "oracle" that computes coordinate transformations and the content of the PROJ database also evolves over time (keep in sync with the EPSG database)
If yyou want to have stable coordinate transformation result, you may need to use advanced API where you fully specify the coordinate pipeline, e.g https://postgis.net/docs/ST_TransformPipeline.html

**Comment by kbevers** [comment]
@eugenemlee It's quite likely not a bug but an improvement you observe from 8.0.0 and onwards. As @rouault says, transformations are improved over time and so are the selection algorithms in PROJ. You can investigate this yourself by checking the various transformations used in different PROJ versions using the `projinfo` application. Here's an example from the latest version:

```
projinfo -s EPSG:28350 -t EPSG:4326 -o PROJ
Candidate operations found: 3
-------------------------------------
Operation No. 1:

unknown id, Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (1), 3 m, Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=50 +south +ellps=GRS80
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1

-------------------------------------
Operation No. 2:

unknown id, Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (2), 3 m, Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=50 +south +ellps=GRS80
  +step +proj=push +v_3
  +step +proj=cart +ellps=GRS80
  +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924
        +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame
  +step +inv +proj=cart +ellps=WGS84
  +step +proj=pop +v_3
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1

-------------------------------------
Operation No. 3:

unknown id, Inverse of Map Grid of Australia zone 50 + GDA94 to WGS 84 (3), 3 m, Australia - Australian Capital Territory; New South 
Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=50 +south +ellps=GRS80
  +step +proj=hgridshift
        +grids=au_icsm_GDA94_GDA2020_conformal_and_distortion.tif
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```

**Comment by busstoptaktik** [comment]
In other words:

- **If you know which transformation you want, just use that. Don't ask PROJ to try to infer one for you.**

Because that inference will be based on a large body of experience and rules-of-thumb, which makes it useful (and helpful) if you do not know what you want, but also implies that you cannot know for sure what you get.

**Comment by eugenemlee** [comment]
Thanks for the explanation @rouault, @kbevers, @busstoptaktik

I'm still puzzled as to why the method for selecting a transformation pipeline is permitted to change in minor versions, let alone patch versions. Although this project does not expressly adhere to semver, it employs a versioning system that might misleadingly suggest stability to its users. This approach seems contradictory to the principle of avoiding breaking changes in non-major releases.

Digging around, I can see now that `pj_get_suggested_operation` was changed in 9.2.0 (https://github.com/OSGeo/PROJ/commit/e1f0b75fbb07d838387e1b2ed128faf15bf39811) which essentially rolled back the changes to before version 8.0.0. To me, this change appears to acknowledge that the modifications from v7 to v8 were erroneous(?).

From the perspective of someone who uses this library downstream, specifically in PostGIS with the `geometry ST_Transform(geometry g1, integer srid);` function, we face a challenge. Our users submit coordinates in various CRS, which we then convert and store in our database in WGS84 format. The issue arises from the PROJ library's frequent adjustments to its transformation algorithm, jeopardizing our ability to accurately revert and return user data in their original CRS.

Additionally, we can't pin our version of PROJ because we rely on AWS RDS. This means we might find ourselves in a situation where AWS updates PROJ from version 8.0.1 to 8.1.0 overnight, leaving us without a reliable method to accurately transform our WGS84 coordinates back to their original GDA94 coordinates. Regardless, I appreciate the clarification. It seems we need to reconsider our approach to data storage and possibly employ `ST_TransformPipeline`, as you recommended, to at least achieve consistent behavior.

**Comment by rouault** [comment]
> I'm still puzzled as to why the method for selecting a transformation pipeline is permitted to change in minor versions, let alone patch versions. Although this project does not expressly adhere to semver, it employs a versioning system that might misleadingly suggest stability to its users. This approach seems contradictory to the principle of avoiding breaking changes in non-major releases.

That's nice theory. But in practice this is impossible for what PROJ does. There are likely millions of possible combinations of (input SRS, output SRS, are of use) and we can't check that the results of such inputs are all stable over time. Some changes are bug fixes, others are regressions. That's life.

> jeopardizing our ability to accurately revert and return user data in their original CRS.

That capability is an illusion. If you need to keep the original data, keep it, do not rely on being able to revert coordinate transformations. Even within the same PROJ version, they are not always symmetric. In some rare cases the transformation suggested for B->A is not the mathematical inverse of A->B.  Standard maths assumptions do not apply in geodesy: no transitivity, no reflexivity. 
For e.g for most purposes WGS84 ~= GDA94 and WGS84 ~= GDA2020 (ie PROJ will get you a null datum shift), but GDA94 != GDA2020 (PROJ will give you a ~ 1.8 metre datum shift)

> Additionally, we can't pin our version of PROJ because we rely on AWS RDS

That's your choice :-) You pay for that service. Hopefully the provider listen to your needs ;-) Otherwise run PostGIS on your own infra (or theirrs) and control which components you put into it ;-)

**Comment by busstoptaktik** [comment]
> Our users submit coordinates in various CRS, which we then convert and store in our database in WGS84 format. The issue arises from the PROJ library's frequent adjustments to its transformation algorithm, jeopardizing our ability to accurately revert and return user data in their original CRS.

@eugenemlee Transformations are empirical contraptions, so this is in general infeasible - you lose information by transformation. If you want to be able to return user data in their original CRS, you should **store** them in their original CRS, and if needed transform at point-of-use

Also, bear in mind that the internal differences between WGS84 realizations is on the order of 2 m, so WGS84 is not a very useful vehicle for lossless roundtripping.

EDIT: I now see @rouault answered essentially the same (but better), while I was writing this

**Comment by oc-k-sakamoto** [comment]
@rouault I would like to ask you one question regarding this issue.

The location of `130.51180595163692 33.287626363135914` seems to be in Japan, but the land conversion for Korea `Tokyo to WGS 84 (5) + Popular Visualization Pseudo-Mercator, 4 m, Republic of Korea (South Korea) - onshore.` is applied. I would like to know the reason why.
