### ISSUE TITLE
Minor version in libproj DLL suffix for MinGW

### ISSUE THREAD

**Issue by visr** [OSGeo/proj.4#4151]
Hi, I help to maintain a [PROJ build for Julia](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/PROJ/build_tarballs.jl), used in [Proj.jl](https://github.com/JuliaGeo/Proj.jl). These builds are cross compiled to the MinGW target, resulting into DLLs with the minor version in the name; `libproj_9_4.dll`. This is implemented in [ProjVersion.cmake](https://github.com/OSGeo/PROJ/blob/9.4.0/cmake/ProjVersion.cmake#L40-L46) and [ProjUtilities.cmake](https://github.com/OSGeo/PROJ/blob/9.4.0/cmake/ProjUtilities.cmake#L37-L63). With this DLL naming new GDAL builds are required for each minor PROJ release, also if they have the same SOVERSION.

Looking at GDAL I get `libgdal-35.dll`, a suffix with the SOVERSION, implemented in https://github.com/OSGeo/gdal/pull/5701. 

Would such behavior also make sense for PROJ?

**Comment by joa-quim** [comment]
Making those unique names based on xx.xx.xx versions is a source of problems (as the present case showed) and a waste. I find my disk full of DLL old versions in artifacts dir that never get removed. I've been building GDAL and PROJ for years with VS (to use in GMT) and I never changed the name of the DLL and also we never had a problem because of it.
So, yes, please adopt a scheme where the DLL names change the least possible.

**Comment by eschnett** [comment]
*ping*
