### ISSUE TITLE
Understanding the forward direction of grid shift corrections

### ISSUE THREAD

**Issue by gmoney1729** [OSGeo/proj.4#4246]
#### Example of problem

I have a bit of a trouble understanding the direction in which grid corrections (from an NTv2 gsb file) are applied. I have a coordinate pair (long-lat) in System A and a gsb file (grid1.gsb) to go from System A to System B. That is, shifts in gsb define the forward direction from System A to B. Both systems use the same ellipsoid (GRS80).

I get different results when using `cct` vs `cs2cs`. Perhaps it's because of my lack of understanding of the transformation direction the command expects. See below the two commands I execute:

```c
echo -2 52 | cs2cs +proj=latlong +nadgrids=grid1.gsb +ellps=GRS80 +to +proj=latlong -f %.10f
```

```c
echo -2 52 | cct -t0 -z0 +proj=latlong +nadgrids=grid1.gsb
```

#### Problem description

I get the expected results using `cs2cs`. It **adds** the shifts to the input coordinates as expected. On the other hand, `cct` results are different because it appears to perform inverse transformation. When I run `cct` with the inverse flag, results are as expected.

#### Expected Output

I'd expect grid shifts to be applied in the forward direction as per the `cct` command above.

#### Environment Information

- PROJ version (`9.4.0`)
- Operation System (Windows 10)

#### Installation method

- OSGEO4W installer

#### Other details

I looked through the source code and observed that in the `fwd_prepare` function in `fwd.cpp`, the function `proj_trans` is called with the inverse direction (`PJ_INV`) for the `hgridshift` of the projection where as the inverse prepare function uses the forward direction. This seems a bit confusing and would appreciate more details.

I also tried the conversion using [Esri's NTv2 routine](https://github.com/Esri/ntv2-file-routines) (no longer maintained) with both forward and inverse flags. The results are as expected, i.e. shifts are **added** to the coordinates I feed in forward direction and [iteratively] subtracted in the reverse.

#### Questions

1. How is the forward direction handled with grid shift files with `cct` and `cs2cs` commands?
2. I'd eventually use System B Lat-Long to project to linear coordinates (using a TM projection). If I used the workaround of adding `+inv` flag to `cct`, how can I build the pipeline to go from System A Lat-Long to System B Northing-Easting. I assume `+inv` flag is applied to the entire pipeline, not just one step of it.

For comparison, when using `cs2cs`, I get the expected output in projected coordinates:
```c
echo -2 52 | cs2cs +proj=latlong +nadgrids=grid1.gsb +ellps=GRS80 +to +proj=tmerc +lat_0=51 +lon_0=-1 +k=1 +x_0=201000 +y_0=402000 -f %.4f
```

**Comment by rouault** [comment]
Yes, the PJ_INV on P->hgridshift seems fishy to me too. This dates back to 90968ff934a348b02f982080f8b7ccf17e037a46 . Perhaps @busstoptaktik has some memories... ?  That code path should be very rarely taken in most standard PROJ code paths, hence this oddity has been unnoticed (assuming it is a bug, but now since it has worked like that since 6 years, we probably don't want to change it).

Anyway, the main take away that you should keep in mind is that using "PROJ.4 style CRS modifiers" like +nadgrids / +geoidgrids / +towgs84 is strongly discouraged when using pipelines / cct. You'd rather want to use an explicit gridshift operator like "+proj=hgridshift +grids=grid1.gsb" instead of stuffing a transformation into an operator like proj=longlat or proj=some_projection_method.
In the cs2cs use case, this goes to a completely different code path, since PROJ 6, which does the right thing and emulates the behaviour of PROJ < 6 era.

If you do ``projinfo -s "+proj=latlong +nadgrids=grid1.gsb +ellps=GRS80 +type=crs" -t "+proj=tmerc +lat_0=51 +lon_0=-1 +k=1 +x_0=201000 +y_0=402000 +ellps=GRS80 +towgs84=0,0,0 +type=crs" -o PROJ --single-line -q`` (note the addition of ``+ellps=GRS80 +togs84=0,0,0`` on the target side, to create a fully qualified datum, since traditionnally nadgrids express the transformation to WGS84, but one can abuse the semantics like that to make any system datum transormation...), you'll get the following pipeline that you can use with cct:
``+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +grids=grid1.gsb +step +proj=tmerc +lat_0=51 +lon_0=-1 +k=1 +x_0=201000 +y_0=402000 +ellps=GRS80``

**Comment by gmoney1729** [comment]
Thank you for the prompt response. The proposed pipeline works well with `cct`. `projinfo` is a handy utility I overlooked.
