### ISSUE TITLE
ReadTheDocs: Warning about potential outdated doc version

### ISSUE THREAD

**Issue by kbevers** [OSGeo/proj.4#4277]
When I open `https://proj.org` I get redirected to `https://proj.org/en/9.5/` and the in screenshot below is displayed:

![billede](https://github.com/user-attachments/assets/ea9e7f55-cd2f-4f44-8e2e-b6e3ba4383dd)

It's probably shown because of the redirect but it sends a bit of a weird signal to users. The warning disappears when switching to the stable version at `https://proj.org/en/stable/`. Is there a way to turn the warning of the 9.5 branch?

**Comment by jjimenezshaw** [comment]
I noticed that today as well. There was a discussion to redirect to `stable` instead of redirecting to `9.5`, and also to set the robots.txt to only allow `stable` there (so search engines are not indexing old versions that may later produce obsolete results).
@rouault had some problems after the last release. Here is the mailing list thread https://lists.osgeo.org/pipermail/proj/2024-September/011528.html

**Comment by rouault** [comment]
Submitted https://github.com/readthedocs/addons/issues/402

**Comment by rouault** [comment]
I've just disabled "Show a notification on non-stable and latest versions" in https://app.readthedocs.org/dashboard/osgeo-proj/addons/edit/ as suggested in https://github.com/readthedocs/addons/issues/402#issuecomment-2407890145.  I assume it will take effect only at the next build of the 9.5 branch

**Comment by rouault** [comment]
fixed
