### ISSUE TITLE
Issue with gdalwarp with proj version from 9.1.0

### ISSUE THREAD

**Issue by aurelienlombard** [OSGeo/proj.4#4300]
#### Problem description

When applying a reprojection using `gdalwarp` of the following file [bogota.tif.zip](https://github.com/user-attachments/files/17586779/bogota.tif.zip), the reprojected file seems wrong.

The problem seems to happen from the version 9.1.0 (no issue when rebuilding gdal with the 9.0.0 version). 

Here are the png explaining the issue :

- before projection :
![bogota](https://github.com/user-attachments/assets/1a36bc16-7815-4c1c-9976-8bbea38b91d0)

- after reprojection in 4326 (using latest proj version):
![bogota_warp_latest](https://github.com/user-attachments/assets/fec7a0cd-9bdb-443a-9eb9-71b2ad959b68)

On this one we can see there's an issue as on the left part of the image there are artefacts corresponding to a duplication of next columns.

- after reprojection in 4326 using proj version 9.0.0:
![bogota_warp_proj900](https://github.com/user-attachments/assets/97c9f3c6-7dc5-4430-86a3-967416e540fd)

This one seems to be the expected one as we do not have these artifacts.

#### Environment Information

- PROJ version : 9.1.0 to latest
- Operation System Information : Mac Sonoma

**Comment by kbevers** [comment]
Perhaps you could share with the group what you've actually done with GDAL

**Comment by jjimenezshaw** [comment]
I just opened the tif file in QGIS for curiosity, and it is placed in Ecuador. That seems wrong to me.
In QGIS it says the left border is a bit over -79.1 degrees, that is right over the limit of https://epsg.org/transformation_1125/Bogota-1975-to-WGS-84-1.html
Probably geolocating correctly the GeoTIFF will help.

**Comment by rouault** [comment]
I've reproduced with "gdalwarp bogota.tif out.tif -t_srs EPSG:4326 -overwrite"

The issue is exactly what @jjimenezshaw identified. The dataset is crossing the validity area of the "Bogota 1975 to WGS 84 (1)" and thus GDAL/PROJ is ocilating between that transformation and a ballpark one:
```
PROJ: Using coordinate operation Inverse of Colombia Bogota zone + Ballpark geographic offset from Bogota 1975 to WGS 84
PROJ: Using coordinate operation Inverse of Colombia Bogota zone + Bogota 1975 to WGS 84 (1)
[ repeated many times ]
```
As far as I can see, this is the expected (per-design) behaviour.

You could possibly override this behaviour by forcing the Bogota 1975 to WGS84 (1) transformation by:
- getting the pipeline with ``projinfo -s EPSG:21897 -t EPSG:4326 --spatial-test intersects -o PROJ -q --single-line`` which outputs:

``
+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=4.59904722222222 +lon_0=-74.0809166666667 +k=1 +x_0=1000000 +y_0=1000000 +ellps=intl +step +proj=push +v_3 +step +proj=cart +ellps=intl +step +proj=helmert +x=307 +y=304 +z=-318 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
``
- and passing it as the -ct value of gdalwarp:

```gdalwarp bogota.tif out2.tif -t_srs EPSG:4326 -overwrite -ct "+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=4.59904722222222 +lon_0=-74.0809166666667 +k=1 +x_0=1000000 +y_0=1000000 +ellps=intl +step +proj=push +v_3 +step +proj=cart +ellps=intl +step +proj=helmert +x=307 +y=304 +z=-318 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1"```

So all in all I don't believe there's a bug

**Comment by aurelienlombard** [comment]
Thank you for this answer. I did not realize that the data was crossing the validity area of the "Bogota 1975 to WGS 84 (1)". In fact the data is completely outside of the CRS it is supposed to be (21897). This data was used by us for some tests, but it should not be used at all. 

The answer is very clear. I think we can close the issue.

But i have just one more question. Why in terms of design it was decided to fallback to the ballbark transformation when some data in the initial image are outside of the limits ?

And as explained the behaviour seems to have changed from 9.0.0 to 9.1.0. What change exactly introduced this new behaviour in the 9.1.0 release ? Was there before a tolerance accepting that for some points that are a bit outside the limits we keep the normal transformation instead of the ballpark one ?

**Comment by rouault** [comment]
> Why in terms of design it was decided to fallback to the ballbark transformation when some data in the initial image are outside of the limits ?

50% of people don't know anything about CRS, datums etc and want "something" more or less plausible, and a ballpark transformation is quite plausible especially at small scales. The other 50% want 0.1 mm precision and errors when it cannot be reached. We can do both, but not at the same time :-)  There's an option to disable ballpark transformations at the PROJ and OGRCoordinateTransformation level, but it isn't accessible through gdalwarp as far as I can remember.

> And as explained the behaviour seems to have changed from 9.0.0 to 9.1.0. What change exactly introduced this new behaviour in the 9.1.0 release ?

Probably a stricter control on the validity area of the transformation to apply. I don't remember. You could "git bisect" if that's really of interest for you ;-)
